services:
  frontend:
    build:
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    mem_limit: 3048m
