import type { OrderType } from '@/types/orderTypes'

export const orders: OrderType[] = [
  {
    id: 'ORD001',
    date: '2024-08-01',
    status: 'Pending',
    pickupLocation: 'Warehouse A aslkdjasd ;lasjd ;l;asljd  alsjd  asl;jd lasd',
    customerName: 'John Doe',
    customerAddress: '123 Elm St, Springfield ksd alskjd alsjdlkajsd kjasd klj alskjd lkj as',
    destinationCity: 'Springfield',
    orderGrandTotal: 99.99,
    currency: 'USD',
    paymentStatus: 'Pending',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 24.68991283091742, lng: 46.673097597127736 },
    shipmentNumber: 'SHIP123456',
    deliveryCompany: 'DHL',
    trackingNumber: '123456789',
    onHoldReason: 'Wrong item',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-05',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    returnShipment: 'No',
    returnDate: '2024-07-10',
    returnStatus: 'Pending',
    cancelReason: 'Defective',
    cancelComment: 'Product is not as described'
  },
  {
    id: 'ORD002',
    date: '2024-08-02',
    status: 'Shipped',
    pickupLocation: 'Warehouse B',
    customerName: 'Jane Smith',
    customerAddress: '456 Oak St, Metropolis',
    destinationCity: 'Metropolis',
    orderGrandTotal: 149.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 24.6898563001661, lng: 46.71405264555091 },
    shipmentNumber: 'SHIP654321',
    deliveryCompany: 'FedEx',
    trackingNumber: '987654321',
    onHoldReason: 'Wrong address',
    onHoldComment: 'Please send me the correct address',
    deliveryDate: '2024-07-10',
    returnShipment: 'Yes',
    returnDate: '2024-07-15',
    returnStatus: 'Shipped',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Damaged',
    cancelComment: 'Product is not as described'
  },
  {
    id: 'ORD003',
    date: '2024-08-03',
    status: 'Delivered',
    pickupLocation: 'Warehouse C',
    customerName: 'Robert Brown',
    customerAddress: '789 Pine St, Gotham',
    destinationCity: 'Gotham',
    orderGrandTotal: 79.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'Visa',
    paymentMethodImageUrl: 'https://logo-marque.com/wp-content/uploads/2020/06/Visa-Logo.png',
    coords: { lat: 24.742244019461864, lng: 46.68191365912011 },
    shipmentNumber: 'SHIP789012',
    deliveryCompany: 'UPS',
    trackingNumber: '456789123',
    onHoldReason: 'Wrong item',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-15',
    returnShipment: 'Yes',
    returnDate: '2024-07-20',
    returnStatus: 'Delivered',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD004',
    date: '2024-08-04',
    status: 'Cancelled',
    pickupLocation: 'Warehouse D',
    customerName: 'Emily Davis',
    customerAddress: '101 Maple St, Star City',
    destinationCity: 'Star City',
    orderGrandTotal: 199.99,
    currency: 'USD',
    paymentStatus: 'Pending',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 24.471702187515547, lng: 39.60849854422776 },
    shipmentNumber: 'SHIP890123',
    deliveryCompany: 'DHL',
    trackingNumber: '789012345',
    onHoldReason: 'Delivery issue',
    onHoldComment: 'Please resolve the delivery issue',
    deliveryDate: '2024-07-20',
    returnShipment: 'Yes',
    returnDate: '2024-07-25',
    returnStatus: 'Cancelled',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD005',
    date: '2024-08-05',
    status: 'Pending',
    pickupLocation: 'Warehouse E',
    customerName: 'Michael Johnson',
    customerAddress: '202 Cedar St, Central City',
    destinationCity: 'Central City',
    orderGrandTotal: 249.99,
    currency: 'USD',
    paymentStatus: 'Canceled',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 24.47127659458407, lng: 39.606413573643835 },
    shipmentNumber: 'SHIP234567',
    deliveryCompany: 'FedEx',
    trackingNumber: '234567890',
    onHoldReason: 'Damaged item',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-10',
    returnShipment: 'No',
    returnDate: '2024-07-10',
    returnStatus: 'Pending',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD006',
    date: '2024-08-06',
    status: 'Shipped',
    pickupLocation: 'Warehouse F',
    customerName: 'Sarah Lee',
    customerAddress: '303 Birch St, Keystone City',
    destinationCity: 'Keystone City',
    orderGrandTotal: 129.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'Visa',
    paymentMethodImageUrl: 'https://logo-marque.com/wp-content/uploads/2020/06/Visa-Logo.png',
    coords: { lat: 24.468653977922898, lng: 39.605014889936 },
    shipmentNumber: 'SHIP345678',
    deliveryCompany: 'UPS',
    trackingNumber: '345678901',
    onHoldReason: 'Wrong item',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-15',
    returnShipment: 'No',
    returnDate: '2024-07-15',
    returnStatus: 'Shipped',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD007',
    date: '2024-08-07',
    status: 'Delivered',
    pickupLocation: 'Warehouse G',
    customerName: 'David Wilson',
    customerAddress: '404 Walnut St, Coast City',
    destinationCity: 'Coast City',
    orderGrandTotal: 89.99,
    currency: 'USD',
    paymentStatus: 'Canceled',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 24.46460977976649, lng: 39.60566093715255 },
    shipmentNumber: 'SHIP456789',
    deliveryCompany: 'DHL',
    trackingNumber: '456789012',
    onHoldReason: 'Payment Pending',
    onHoldComment: 'Please resolve the payment issue',
    deliveryDate: '2024-07-20',
    returnShipment: 'No',
    returnDate: '2024-07-20',
    returnStatus: 'Delivered',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD008',
    date: '2024-08-08',
    status: 'Cancelled',
    pickupLocation: 'Warehouse H',
    customerName: 'Laura Moore',
    customerAddress: '505 Cherry St, Bludhaven',
    destinationCity: 'Bludhaven',
    orderGrandTotal: 179.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 26.3350978, lng: 50.1106446 },
    shipmentNumber: 'SHIP567890',
    deliveryCompany: 'FedEx',
    trackingNumber: '567890123',
    onHoldReason: 'Delivery issue',
    onHoldComment: 'Please resolve the delivery issue',
    deliveryDate: '2024-07-25',
    returnShipment: 'No',
    returnDate: '2024-07-25',
    returnStatus: 'Cancelled',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD009',
    date: '2024-08-09',
    status: 'Pending',
    pickupLocation: 'Warehouse I',
    customerName: 'Kevin Clark',
    customerAddress: '606 Willow St, National City',
    destinationCity: 'National City',
    orderGrandTotal: 139.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'Visa',
    paymentMethodImageUrl: 'https://logo-marque.com/wp-content/uploads/2020/06/Visa-Logo.png',
    coords: { lat: 26.3270778, lng: 50.1106446 },
    shipmentNumber: 'SHIP678901',
    deliveryCompany: 'UPS',
    trackingNumber: '678901234',
    onHoldReason: 'Weather Delays',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-10',
    returnShipment: 'No',
    returnDate: '2024-07-10',
    returnStatus: 'Pending',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD010',
    date: '2024-08-10',
    status: 'Shipped',
    pickupLocation: 'Warehouse J',
    customerName: 'Jessica Taylor',
    customerAddress: '707 Poplar St, Starling City',
    destinationCity: 'Starling City',
    orderGrandTotal: 119.99,
    currency: 'USD',
    paymentStatus: 'Pending',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 21.57692285097066, lng: 39.165928502913175 },
    shipmentNumber: 'SHIP789012',
    deliveryCompany: 'DHL',
    trackingNumber: '789012345',
    onHoldReason: 'Wrong item',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-15',
    returnShipment: 'No',
    returnDate: '2024-07-15',
    returnStatus: 'Shipped',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD011',
    date: '2024-08-11',
    status: 'Delivered',
    pickupLocation: 'Warehouse K',
    customerName: 'Brian Martin',
    customerAddress: '808 Ash St, Freeland',
    destinationCity: 'Freeland',
    orderGrandTotal: 159.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 22.57692285097066, lng: 40.165928502913175 },
    shipmentNumber: 'SHIP890123',
    deliveryCompany: 'FedEx',
    trackingNumber: '890123456',
    onHoldReason: 'Holiday Schedule',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-20',
    returnShipment: 'No',
    returnDate: '2024-07-20',
    returnStatus: 'Delivered',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD012',
    date: '2024-08-12',
    status: 'Cancelled',
    pickupLocation: 'Warehouse L',
    customerName: 'Amanda White',
    customerAddress: '909 Redwood St, Smallville',
    destinationCity: 'Smallville',
    orderGrandTotal: 189.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'Visa',
    paymentMethodImageUrl: 'https://logo-marque.com/wp-content/uploads/2020/06/Visa-Logo.png',
    coords: { lat: 21.57692285097066, lng: 41.165928502913175 },
    shipmentNumber: 'SHIP234567',
    deliveryCompany: 'UPS',
    trackingNumber: '234567890',
    onHoldReason: 'Delivery issue',
    onHoldComment: 'Please resolve the delivery issue',
    deliveryDate: '2024-07-25',
    returnShipment: 'No',
    returnDate: '2024-07-25',
    returnStatus: 'Cancelled',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD013',
    date: '2024-08-13',
    status: 'Pending',
    pickupLocation: 'Warehouse M',
    customerName: 'Matthew Harris',
    customerAddress: '101 Pineapple St, Atlantis',
    destinationCity: 'Atlantis',
    orderGrandTotal: 199.99,
    currency: 'USD',
    paymentStatus: 'Pending',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 23.7749295, lng: 45.4194155 },
    shipmentNumber: 'SHIP345678',
    deliveryCompany: 'DHL',
    trackingNumber: '345678901',
    onHoldReason: 'Payment Pending',
    onHoldComment: 'Please resolve the payment issue',
    deliveryDate: '2024-07-10',
    returnShipment: 'No',
    returnDate: '2024-07-10',
    returnStatus: 'Pending',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD014',
    date: '2024-08-14',
    status: 'Shipped',
    pickupLocation: 'Warehouse N',
    customerName: 'Olivia Jackson',
    customerAddress: '202 Coconut St, Oa',
    destinationCity: 'Oa',
    orderGrandTotal: 109.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 22.57692285097066, lng: 43.165928502913175 },
    shipmentNumber: 'SHIP456789',
    deliveryCompany: 'FedEx',
    trackingNumber: '456789012',
    onHoldReason: 'Freight Consolidation',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-15',
    returnShipment: 'No',
    returnDate: '2024-07-15',
    returnStatus: 'Shipped',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD015',
    date: '2024-08-15',
    status: 'Delivered',
    pickupLocation: 'Warehouse O',
    customerName: 'Joshua Robinson',
    customerAddress: '303 Mango St, Krypton',
    destinationCity: 'Krypton',
    orderGrandTotal: 149.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'Visa',
    paymentMethodImageUrl: 'https://logo-marque.com/wp-content/uploads/2020/06/Visa-Logo.png',
    coords: { lat: 19.432608, lng: -99.133208 },
    shipmentNumber: 'SHIP567890',
    deliveryCompany: 'UPS',
    trackingNumber: '567890123',
    onHoldReason: 'Weather Delays',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-20',
    returnShipment: 'No',
    returnDate: '2024-07-20',
    returnStatus: 'Delivered',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD016',
    date: '2024-08-16',
    status: 'Cancelled',
    pickupLocation: 'Warehouse P',
    customerName: 'Sophia Lewis',
    customerAddress: '404 Lemon St, Xandar',
    destinationCity: 'Xandar',
    orderGrandTotal: 89.99,
    currency: 'USD',
    paymentStatus: 'Pending',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 20.593684, lng: -78.96288 },
    shipmentNumber: 'SHIP678901',
    deliveryCompany: 'DHL',
    trackingNumber: '678901234',
    onHoldReason: 'Delivery issue',
    onHoldComment: 'Please resolve the delivery issue',
    deliveryDate: '2024-07-25',
    returnShipment: 'No',
    returnDate: '2024-07-25',
    returnStatus: 'Cancelled',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD017',
    date: '2024-08-17',
    status: 'Pending',
    pickupLocation: 'Warehouse Q',
    customerName: 'Daniel Walker',
    customerAddress: '505 Strawberry St, Knowhere',
    destinationCity: 'Knowhere',
    orderGrandTotal: 129.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 21.57692285097066, lng: 39.165928502913175 },
    shipmentNumber: 'SHIP789012',
    deliveryCompany: 'FedEx',
    trackingNumber: '789012345',
    onHoldReason: 'Payment Pending',
    onHoldComment: 'Please resolve the payment issue',
    deliveryDate: '2024-07-10',
    returnShipment: 'No',
    returnDate: '2024-07-10',
    returnStatus: 'Pending',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD018',
    date: '2024-08-18',
    status: 'Shipped',
    pickupLocation: 'Warehouse R',
    customerName: 'Emma Lee',
    customerAddress: '606 Blueberry St, Tatooine',
    destinationCity: 'Tatooine',
    orderGrandTotal: 179.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'Visa',
    paymentMethodImageUrl: 'https://logo-marque.com/wp-content/uploads/2020/06/Visa-Logo.png',
    coords: { lat: 22.57692285097066, lng: 40.165928502913175 },
    shipmentNumber: 'SHIP890123',
    deliveryCompany: 'UPS',
    trackingNumber: '890123456',
    onHoldReason: 'Wrong item',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-15',
    returnShipment: 'No',
    returnDate: '2024-07-15',
    returnStatus: 'Shipped',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD019',
    date: '2024-08-19',
    status: 'Delivered',
    pickupLocation: 'Warehouse S',
    customerName: 'James Scott',
    customerAddress: '707 Raspberry St, Endor',
    destinationCity: 'Endor',
    orderGrandTotal: 99.99,
    currency: 'USD',
    paymentStatus: 'Pending',
    paymentMethod: 'Mastercard',
    paymentMethodImageUrl: 'https://logos-world.net/wp-content/uploads/2020/09/Mastercard-Logo.png',
    coords: { lat: 24.7749295, lng: 46.4194155 },
    shipmentNumber: 'SHIP234567',
    deliveryCompany: 'DHL',
    trackingNumber: '234567890',
    onHoldReason: 'Holiday Schedule',
    onHoldComment: 'Please send me the correct item',
    deliveryDate: '2024-07-20',
    returnShipment: 'No',
    returnDate: '2024-07-20',
    returnStatus: 'Delivered',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  },
  {
    id: 'ORD020',
    date: '2024-08-20',
    status: 'Cancelled',
    pickupLocation: 'Warehouse T',
    customerName: 'Isabella Allen',
    customerAddress: '808 Blackberry St, Naboo',
    destinationCity: 'Naboo',
    orderGrandTotal: 159.99,
    currency: 'USD',
    paymentStatus: 'Paid',
    paymentMethod: 'PayPal',
    paymentMethodImageUrl: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/250_Paypal_logo-512.png',
    coords: { lat: 25.7749295, lng: 44.4194155 },
    shipmentNumber: 'SHIP345678',
    deliveryCompany: 'FedEx',
    trackingNumber: '345678901',
    onHoldReason: 'Delivery issue',
    onHoldComment: 'Please resolve the delivery issue',
    deliveryDate: '2024-07-25',
    returnShipment: 'No',
    returnDate: '2024-07-25',
    returnStatus: 'Cancelled',
    DCReturnReason: 'Damaged',
    customerReturnReason: 'Defective',
    customerReturnComment: 'Product is not as described',
    cancelReason: 'Wrong item',
    cancelComment: 'Please send me the correct item'
  }
]
